SolanisHotel.WebUI/Controllers/ReservationController.cs
using Microsoft.AspNetCore.Mvc;
using SolanisHotel.BLL.DTOs;
using SolanisHotel.BLL.Managers.Abstracts;
using SolanisHotel.BLL.Results;
using SolanisHotel.BLL.ViewModels;
using SolanisHotel.WebUI.Extensions;
using System.Security.Claims;

namespace SolanisHotel.WebUI.Controllers
{
    public class ReservationController : Controller
    {
        readonly ILogger<ReservationController> _logger;

        readonly IReservationManager _reservationMan;

        public ReservationController(IReservationManager reservationMan, ILogger<ReservationController> logger)
        {
            _reservationMan = reservationMan;
            _logger = logger;
        }

        //----------//----------//

        [Route("Reservation/Create")]
        public IActionResult MakeReservation() => View();

        [HttpPost]
        [Route("Reservation/Create")]
        public async Task<IActionResult> MakeReservation(ReservationVM rvm)
        {
            CustomerDTO customerDTO = new CustomerDTO
            {
                Email = User.FindFirstValue(ClaimTypes.Email)!
            };
            rvm.CustomerDTO = customerDTO;

            OperationResult oR = await _reservationMan.CreateReservation(rvm);
            if (oR.Success)
            {
                HttpContext.Session.SetObject("tempReservation", (ReservationVM)oR.Data!);

                return RedirectToAction("ShowReservation");
            }
            else
            {
                if (oR.Exception != null)
                {
                    TempData["ReservationError"] = $"{oR.Message}"; //Todo:Hata mesajını log olarak kaydedebilirim. (LowPriority)
                }
                else
                {
                    TempData["ReservationError"] = $"{oR.Message}";
                }
                return View();
            }
        }

        //-----//-----//

        [Route("Reservation/Show")]
        public IActionResult ShowReservation()
        {
            ReservationVM? tempReservation = HttpContext.Session.GetObject<ReservationVM>("tempReservation");
            return (tempReservation != null) ? View(tempReservation) : RedirectToAction("Error", "Home");
        }

        //-----//-----//

        [HttpPost]
        public async Task<IActionResult> CancelReservation()
        {
            ReservationVM? tempReservation = HttpContext.Session.GetObject<ReservationVM>("tempReservation");
            if (tempReservation != null)
            {
                HttpContext.Session.Clear();

                OperationResult oR = await _reservationMan.CancelReservation(tempReservation);

                return oR.Success ? RedirectToAction("Index", "Home") : RedirectToAction("Error", "Home");
            }
            return RedirectToAction("Index", "Home");
        }

        //----------//----------//
    }
}

SolanisHotel.WebUI/Views/Shared/Partial/_FooterPartialView.cshtml
<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - SolanisHotel.WebUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>

SolanisHotel.WebUI/Views/Shared/Partial/_HeaderPartialView.cshtml
<header>



    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SolanisHotel.WebUI</a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" asp-controller="Reservation" asp-action="MakeReservation">Rezervasyon Yap</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Kampanyalar</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Hakkımızda</a>
                    </li>

                    @*class="nav-link disabled" / class="nav-link active" / class="nav-link"*@
                </ul>

                <ul class="navbar-nav ms-auto">

                    @if (User.Identity!.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a asp-controller="Account" asp-action="Profile" class="nav-link">Profil</a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Account" asp-action="Logout" class="nav-link">Çıkış Yap</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a asp-controller="Account" asp-action="Login" class="nav-link">Giriş Yap</a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Account" asp-action="Register" class="nav-link">Kayıt Ol</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>

SolanisHotel.WebUI/Views/Shared/Partial/_SelectedRoomsInfo.cshtml
@model ReservationVM

<div class="card text-center">
    <div class="card-header">
        <h3>Rezervasyon Bilgileriniz</h3>
    </div>

    <div class="card-body">
        <h4 class="card-title">Genel Bilgiler</h4>

        <div class="mb-2">
            <span><strong>Giriş Tarihi:</strong> @Model.CheckIn.ToLongDateString() <strong>Çıkış Tarihi:</strong> @Model.CheckOut.ToLongDateString()</span>
        </div>
        <div class="mb-2">
            <span><strong>Toplam Misafir Sayısı:</strong> @Model.ReservationDTO.NumberOfGuests</span>
        </div>
        <div class="mb-2">
            <span><strong>Toplam Oda Sayısı:</strong> @Model.ReservationDTO.NumberOfRooms</span>
        </div>
        <div>
            @if (Model.ReservationDTO.NumberOfExtraBeds > 0)
            {
                <span>@Model.ReservationDTO.NumberOfExtraBeds Adet Ekstra Yatak</span>

            }
            else
            {
                <span>Ekstra Yatak Gerekmiyor</span>
            }
        </div>
    </div>

    <hr />

    <div class="row justify-content-center">
        <h4 class="card-title">Oda Bilgileri</h4>
        @foreach (RoomDTO room in Model.SuitableRoomsDTO)
        {
            <div class="col-4">

                <div class="card-body">

                    <div class="mb-2">
                        <span><strong>Oda Numarası:</strong> @room.RoomNumber</span>
                    </div>
                    <div class="mb-2">
                        <span><strong>Günlük Fiyat:</strong> @room.Price.ToString("C")</span>
                    </div>
                    <div>
                        <span><strong>Kapasite:</strong> @room.Capacity</span>
                    </div>

                </div>

            </div>
        }
    </div>

    <hr />

    <div class="card-body">
        <h4 class="card-title">Ödeme Bilgileri</h4>

        <div class="mb-2">
            <span><strong>Gecelik Fiyat (Oda Başına):</strong> @Model.SuitableRoomsDTO.FirstOrDefault()?.Price.ToString("C")</span>
        </div>

        @if (Model.ReservationDTO.NumberOfExtraBeds > 0)
        {
            decimal extraBedPrice = Model.SuitableRoomsDTO.FirstOrDefault().Price / 3;

            <div class="mb-2">
                <span><strong>Ekstra Yatak Fiyatı (Yatak Başına):</strong> @extraBedPrice.ToString("C")</span>
            </div>
        }

        <div>
            <span><strong>Toplam Fiyat:</strong> @Model.ReservationDTO.TotalPrice.ToString("C")</span>
        </div>

    </div>
</div>